# I copied this config from
#   https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Learning-Environment-Create-New.md
# 
# To run a training session, first follow the steps in this guide to set up
# a conda environment with the the mlagents python package:
#   https://docs.google.com/document/d/1w5H3TNS3VK7YsBsC7xzOf-vR2sjMl3NGQVsO4iUAH1Q/edit?tab=t.0
# Then run this:
#   $ conda activate mlagents
#   $ mlagents-learn agent-training-configs/config_v0.yaml --run-id=my_run_id --train
#   (then press play on the "Test Scene Agent" scene in Unity)
# This will create a new model in the Assets/results/ directory with the name my_run_id.
# To use the model during inference, open up the paddleP2 gameObject in the Unity inspector
#   and select your model in the "Model" field in the Behavior Parameters component.
behaviors:
  Paddle:
    trainer_type: ppo
    checkpoint_interval: 10000 # Keep this small so train_models.py can save a recent model when it identifies each AI difficulty stage
    keep_checkpoints: 10
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 4.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000
environment_parameters:
  stage:
    curriculum:
      - name: EasyAIStage
        completion_criteria:
          behavior: Paddle
          measure: reward
          threshold: 3.0
          require_reset: true  # Forces a reset between lessons
        value: 0.0
      - name: MediumAIStage
        completion_criteria:
          behavior: Paddle
          measure: reward
          threshold: 25.0
          require_reset: true  # Forces a reset between lessons
        value: 3.0  # Stage 3 for quadrant brick mode
      - name: HardAIStage
        completion_criteria:
          behavior: Paddle
          measure: reward
          threshold: 60.0
          require_reset: true  # Forces a reset between lessons
        value: 4.0